config/routes.rb
FriendmaybeDevise::Application.routes.draw do

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}, :skip => [:sessions, :passwords, :registrations] do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  authenticated :user do
    root to: "home_pages#home"
    post "/login", to: "home_pages#login"
    post "/location" , to: "home_pages#location"
    post "/notification", to: "home_pages#notification"
    get "/feedback", to: "home_pages#feedback"
  end
  root to: "login_pages#login"
  match "/help", to: "login_pages#help"
  match "/contact", to: "login_pages#contact"
  get "/feedback", to: "login_pages#feedback"
  get "/privacy", to: "login_pages#privacy"

  get "/anonymous", to: "anonymous#anonymous"
  post "/anonymouslogin", to: "anonymous#anonymouslogin"
  post "/location" , to: "anonymous#location"
  post "/notification", to: "anonymous#notification"

end

app/controllers/login_pages_controller.rb
class LoginPagesController < ApplicationController


  def login
    @onlineUsers = Rails.cache.read('onlineUsers')
    if @onlineUsers.nil?
      @onlineUsers = 0
    end
  end

  def help
  end

  def contact
  end

  def privacy

  end
  def feedback
    Feedback.create({
                        user_id: 0,
                        feedback: params['feedback']
                    })
    respond_to do |format|
      format.js { render json: {status: 'feedback'}}
    end
  end
end

app/helpers/login_pages_helper.rb
module LoginPagesHelper
end

app/views/login_pages/_header.html.erb
<header class="navbar-fixed-top navbar navbar-inverse">
  <div class="navbar-inner">
    <%= link_to "Friendmaybe", root_path, id: "logo" %>
    <em style="float:left">beta</em>
    <nav>
      <ul class="nav pull-right">
        <li><a><strong style="font-size: 18px;"><%= @onlineUsers %></strong> <em> online users</em></a></li>
        <li><%= link_to 'feedback' , '#', style: "padding-top: 10px; padding-bottom: 10px", class: 'feedback' %></li>
        <li class="divider-vertical"></li>
        <li><%= link_to "Terms & Privacy", privacy_path, class: "", title: "Terms & Privacy" %></li>
        <li><%= link_to "About Us", contact_path %></li>
        <li><%= link_to "Help", help_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/login_pages/_loginbox.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
  <div class="loginbtn span6">
    <div class="span6" style="border-right:1px solid #808080;text-align: center; padding-right: 10px;min-width: 200px;">
      <div style="margin-bottom: 10px">
        Find a new friend near by you where ever you go. You can choose to remember the user you are chatting with or you choose only one time chat. The chat will be completely anonymous
        You can try it as anonymous.
      </div>
        <div class="span3"></div>
        <%= link_to "Anonymous", anonymous_path, class: "auth-btn btn btn btn-primary span6", title: "log in Anonymously" %>
    </div>
    <div class="span6" style="min-width: 200px;">
    <fieldset >
      <div style="font-size: 21px;line-height: 40px;margin-bottom: 20px;text-align: center">Sign-in</div>
        <div>
          <%= link_to "Facebook", user_omniauth_authorize_path(:facebook), class: "auth-btn btn btn-primary span6", title: "log in with Facebook" %>
          <%= link_to "Google", user_omniauth_authorize_path(:google_oauth2), class: "auth-btn btn btn-primary span6", title: "log in with Google" %>

        </div>
      <!--<p>Google login has been disabled to testing</p>-->

    </fieldset>
      </div>
  </div>
        </div></div></div>

app/views/login_pages/contact.html.erb
<%= render 'login_pages/header' %>

<div class="container-fluid">
  <div class="container container-body">
    <div style="text-align: center"><h3>About Us</h3></div>
    <p><h4>Developer:</h4></p>
    <p><strong>Name:</strong>Pankaj Kumar<br/>
      <strong>Email:</strong>pankaj4u4m@gmail.com<br/>
      <strong>Contacts:</strong> +918977674772
    </p>
  </div>
</div>

app/views/login_pages/help.html.erb
<%= render 'login_pages/header' %>

<div class="container-fluid">
  <div class="container container-body">
    <div style="text-align: center"><h3>Help</h3></div>
    <p>For any query please mail to pankaj4u4m@gmail.com</p>
  </div>
</div>

app/views/login_pages/login.html.erb
<%= render 'login_pages/header' %>

<body class="login-body">
<div>
  <div class="login-wrapper">
    <div class="login-description">
      Friendmaybe
    </div>
    <em style="text-align: right;padding-top: 15px;display: block;">
      lets know people
    </em>
  </div>
</div>
<%= render 'login_pages/loginbox' %>
<!--<div class="login-privacy">-->
<!--<p>Friendmaybe is a great way to interact with people near by you. When you are in friendmaybe we pick a random near by user and-->
<!--let you chat with each other. This interaction in complete anonymous and you can disconnect it anytime you want.-->
<!--However if you sigin in you can remember them and chat with them later. </p>-->

<!--</div>-->
</div>
</div>
</body>

app/views/login_pages/privacy.html.erb
<%= render 'login_pages/header' %>

<div class="container-fluid">
  <div class="container container-body">
    <div style="text-align: center"><h3>Privacy Policy</h3></div>
    <p>This privacy policy sets out how Friendmaybe uses and protects any information that you give when you use this
      website.</p>

    <p>Friendmaybe is committed to ensuring that your privacy is protected. However privacy cannot be guaranteed as nothing in
      the world is perfect. METLY DOESN'T ACCEPT ANY KIND OF LIABLE OR RESPONSIBLE FOR ANY KIND OF DAMAGE OR LOSS HAPPEN
      WHILE USING THE SERVICE </p>

    <h4>User Privacy:</h4>

    <p>Friendmaybe Uses Facebook or Google login to keep track of your remembered people and associate the same when you login
      in and store the state when you logout. Friendmaybe only fetch VERY BASIC information like emailId, name, age and gender
      etc. All these information is only used for internal purpose for account management and best matching with
      stranger.</p>

    <p>While interacting with stranger Friendmaybe may share your gender and age only for initial introduction. However it
      only shares if you provide these information to Friendmaybe else it will not. Friendmaybe don't share your name to the stranger.
      But if you want to remember the stranger for later interaction you will share your name only. It is done so that you
      can know the real name of stranger you are remembering.</p>

    <p>There is no way stranger/remembered users can know your facebook or google information.</p>

    <p>However If you still concern about user privacy you can still enjoy the Friendmaybe service without sign in and no information will be stored.</p>

    <h4>Use of cookies:</h4>

    <p>Friendmaybe uses cookies to store recognize the user so that it can associate with your account and you don't need to
      signin each time you visit the site.</p>

    <h4>Shared with Friendmaybe:</h4>

    <p>Friendmaybe may logged your request and response for internal use and quality purpose which also includes your public
      IP address.</p>

    <p>Friendmaybe keep history of your chat with rememered yours only. Chatting with strangers are not stored</p>

    <p>Friendmaybe may change this policy from time to time by updating this page. You should check this page from time to
      time to ensure that you are happy with any changes.</p>
  </div>
</div>